tf_prefix:
  controller_manager:
    ros__parameters:
      update_rate: 500 # Hz
      joint_state_broadcaster:
        type: joint_state_broadcaster/JointStateBroadcaster
      diff_drive_control:
          type: diff_drive_controller/DiffDriveController

  joint_state_broadcaster:
    ros__parameters:
      joints:
        - tf_prefix/front_left_wheel
        - tf_prefix/rear_left_wheel
        - tf_prefix/front_right_wheel
        - tf_prefix/rear_right_wheel
      interfaces:
        - position
        - velocity
        - effort 
      use_sim_time: True
  diff_drive_control:
    ros__parameters:
      left_wheel_names:
        - tf_prefix/front_left_wheel
        - tf_prefix/rear_left_wheel
      right_wheel_names:
        - tf_prefix/front_right_wheel
        - tf_prefix/rear_right_wheel
      wheels_per_side: 2
      wheel_separation: 0.58306
      wheel_radius: 0.16459
      use_stamped_vel: True
      use_sim_time: True

      linear.x.has_velocity_limits: true
      linear.x.has_acceleration_limits: false
      linear.x.max_velocity: 1.0
      linear.x.min_velocity: -1.0
      linear.x.max_acceleration: 1.0

      angular.z.has_velocity_limits: True
      angular.z.has_acceleration_limits: false
      angular.z.max_velocity: 0.8
      angular.z.min_velocity: -0.8
      angular.z.max_acceleration: 0.5
      angular.z.min_acceleration: -0.5


