tf_prefix:
  controller_manager:
    ros__parameters:
      update_rate: 500 # Hz
      joint_state_broadcaster:
        type: joint_state_broadcaster/JointStateBroadcaster
      ackerman_control:
        type: ackermann_steering_controller/AckermannSteeringController
      fw_contr:
        type: forward_command_controller/ForwardCommandController

  joint_state_broadcaster:
    ros__parameters:
      joints:
        - tf_prefix/re_right_joint
        - tf_prefix/re_left_joint
        - tf_prefix/fr_steer_left_joint
        - tf_prefix/fr_steer_right_joint
        
      interfaces:
        - position
        - velocity
        - effort 
      use_sim_time: True

  ackerman_control:
    ros__parameters:
      front_steering: True
      rear_wheels_names:
        - tf_prefix/re_right_joint
        - tf_prefix/re_left_joint
      front_wheels_names:
        - tf_prefix/fr_steer_left_joint
        - tf_prefix/fr_steer_right_joint
      base_frame_id: tf_prefix/base_link
      odom_frame_id: tf_prefix/odom
      enable_odom_tf: True
      front_wheel_track: 0.705
      rear_wheel_track: 0.705
      wheelbase: 0.650
      front_wheels_radius: 0.330
      rear_wheels_radius: 0.330
      use_stamped_vel: True
      use_sim_time: True
  fw_contr:
    ros__parameters:
      joints:
        - tf_prefix/fr_steer_left_joint
        - tf_prefix/fr_steer_right_joint
      interface_name: position

